"""muse-chain CLI: run the E2E chain over the corpus registry.

Usage:
  python3 tools/muse_chain/cli.py --all [--report docs/chain-report.md]
  python3 tools/muse_chain/cli.py --work bach/bwv227.1.mxl
  python3 tools/muse_chain/cli.py --determinism
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))  # tools/
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ir"))

from muse_chain import REGISTRY, check_determinism, run_all, run_work  # noqa: E402

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEFAULT_REPORT = os.path.join(REPO, "docs", "chain-report.md")


def format_report(results, determinism):
    lines = [
        "# Chain report — E2E harness",
        "",
        "Generated by tools/muse_chain. Stages: parse(W1) → pack(S2) → "
        "container(S5) → decode(P1-stub) → verify(W4) → render(P2).",
        "",
        f"Determinism (two full runs, identical artifacts): "
        f"{'PASS' if not determinism else 'FAIL: ' + ', '.join(determinism)}",
        "",
        "| Work | parse | pack | container | decode | verify | render |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in results:
        cells = {s.stage.split("(")[0]: s.status for s in r.stages}
        lines.append(
            f"| {r.work_id} | {cells.get('parse', '—')} | {cells.get('pack', '—')} "
            f"| {cells.get('container', '—')} | {cells.get('decode', '—')} "
            f"| {cells.get('verify', '—')} | {cells.get('render', '—')} |"
        )
    lines.append("")
    failures = [r for r in results if not r.ok]
    if failures:
        lines.append("## Failures")
        for r in failures:
            for s in r.stages:
                if s.status == "FAIL":
                    lines.append(f"- **{r.work_id}** stage `{s.stage}`: {s.detail}")
    else:
        lines.append("No failures. Skips are stage-stubs (P1 sandboxed decoder, "
                     "P2 renderer) and over-budget W4 diffs, as designed.")
    return "\n".join(lines) + "\n"


def print_result(r):
    for s in r.stages:
        mark = {"PASS": "OK  ", "FAIL": "FAIL", "SKIP": "SKIP"}[s.status]
        print(f"{mark} {r.work_id:22} {s.stage:16} {s.detail}")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="muse-chain", description=__doc__)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--work")
    ap.add_argument("--determinism", action="store_true",
                    help="run the registry twice, compare artifacts")
    ap.add_argument("--report", default=None)
    args = ap.parse_args(argv)

    if args.determinism:
        mismatches = check_determinism()
        if mismatches:
            print(f"FAIL  nondeterministic artifacts: {mismatches}")
            return 1
        print(f"OK  determinism: {len(REGISTRY)} works, two runs, identical artifacts")
        return 0

    if args.work:
        rel = args.work
        wid = next((w for w, r in REGISTRY if r == rel), os.path.basename(rel))
        results = [run_work(wid, rel)]
    elif args.all:
        results = run_all()
    else:
        ap.error("need --all, --work, or --determinism")

    for r in results:
        print_result(r)

    report_path = args.report or (DEFAULT_REPORT if args.all else None)
    if report_path:
        mismatches = check_determinism() if args.all else []
        with open(report_path, "w") as f:
            f.write(format_report(results, mismatches))
        print(f"\n→ {report_path}")

    return 0 if all(r.ok for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
