"""muse-analyze CLI: pattern report per work or full corpus.

Usage:
  python3 tools/muse_analyze/cli.py <file>              # per-work
  python3 tools/muse_analyze/cli.py --all               # full corpus → docs/analysis-report.md
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ir"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from muse_ir import load  # noqa: E402
from muse_analyze import analyze  # noqa: E402

CORPUS_FILES = [
    "bach/bwv227.1.mxl",
    "bach/bwv227.3.mxl",
    "bach/bwv227.7.mxl",
    "bach/bwv227.11.mxl",
    "byrd/1-Kyrie.mid",
    "byrd/2-Gloria.mid",
    "byrd/3-Credo.mid",
    "byrd/4-Sanctu.mid",
    "byrd/5-Bened.mid",
    "byrd/6-Agnus.mid",
    "schubert/death-and-the-maiden.mxl",
    "beethoven/beethoven-sym5-mov1.xml",
    "beethoven/beethoven-sym9.xml",
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("file", nargs="?")
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args()

    here = os.path.dirname(__file__)
    corpus = os.path.join(here, "..", "..", "corpus")
    report_path = os.path.join(here, "..", "..", "docs", "analysis-report.md")

    if args.all:
        sections = ["# Analysis report — W3 full corpus\n",
                    "\nGenerated by tools/muse_analyze. Counts: distinct patterns per class.\n"]
        for rel in CORPUS_FILES:
            path = os.path.join(corpus, rel)
            try:
                rep = analyze(load(path), name_hint=rel)
            except Exception as e:
                sections.append(f"\n## {rel}\n\nERROR: {e}\n")
                continue
            sections.append("\n## " + rel + "\n")
            sections.append(rep.summary() + "\n")
            print(f"OK  {rel}: exact {len(rep.exact)}, transposed {len(rep.transposed)}, "
                  f"ostinato {len(rep.ostinato)}, imitative {len(rep.imitative)}, "
                  f"curve {len(rep.delta_curve)}")
        with open(report_path, "w") as f:
            f.write("\n".join(sections))
        print(f"\n→ {report_path}")
        return

    if not args.file:
        ap.error("need a file or --all")

    rep = analyze(load(args.file), name_hint=args.file)
    print(rep.summary())


if __name__ == "__main__":
    main()
